# Generated by Django 5.2.12 on 2026-04-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True, max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gp", "General Practitioner (GP)"),
                            ("aesthetic", "Aesthetic / Skin"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "is_medical",
                    models.BooleanField(
                        default=False,
                        help_text="True when Gemini indicates a verified medical/clinic context.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Combined Maps/snippet text used for enrichment.",
                    ),
                ),
                ("specialties", models.JSONField(blank=True, default=list)),
                ("doctor_names", models.JSONField(blank=True, default=list)),
                (
                    "serper_cid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Serper / Google Maps cid when available (deduplication).",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["website"], name="leads_clini_website_a054dd_idx"
                    ),
                    models.Index(
                        fields=["category", "is_medical"],
                        name="leads_clini_categor_c9cea3_idx",
                    ),
                ],
            },
        ),
    ]
