# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinic",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="clinic",
            old_name="category",
            new_name="clinic_type",
        ),
        migrations.RemoveIndex(
            model_name="clinic",
            name="leads_clini_categor_c9cea3_idx",
        ),
        migrations.RemoveIndex(
            model_name="clinic",
            name="leads_clini_website_a054dd_idx",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="is_medical",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="description",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="specialties",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="doctor_names",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="serper_cid",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="clinic",
            name="source_url",
            field=models.TextField(
                blank=True,
                help_text="Google Maps URL from Serper for this place.",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="is_ai_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clinic",
            name="ai_analysis",
            field=models.TextField(
                blank=True,
                help_text="Gemini reasoning and classification notes.",
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="clinic_type",
            field=models.CharField(
                choices=[
                    ("gp", "GP"),
                    ("aesthetic", "Aesthetic"),
                    ("dental", "Dental"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AlterModelOptions(
            name="clinic",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(fields=["clinic_type"], name="leads_cl_ty_idx"),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(fields=["is_ai_processed"], name="leads_cl_ai_idx"),
        ),
        migrations.AddConstraint(
            model_name="clinic",
            constraint=models.UniqueConstraint(
                fields=("name", "address"),
                name="unique_clinic_name_address",
            ),
        ),
    ]
