# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_clinic_lead_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="has_mounjaro",
            field=models.BooleanField(
                default=False,
                help_text="True when Mounjaro, Zepbound, or tirzepatide is mentioned in supplied text.",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="is_chain",
            field=models.BooleanField(
                default=False,
                help_text="True when Gemini detects several branches / multi-outlet chain signals.",
            ),
        ),
    ]
