# Generated by Django 5.2.12 on 2026-04-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_clinic_chain_mounjaro"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinic",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Clinic",
                "verbose_name_plural": "Clinics",
            },
        ),
    ]
