# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_alter_clinic_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="search_city",
            field=models.CharField(
                blank=True,
                help_text="City / area used for the Serper hunt that captured this lead.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="search_query",
            field=models.CharField(
                blank=True,
                help_text="Maps search query used for the Serper hunt.",
                max_length=255,
                null=True,
            ),
        ),
    ]
