# Generated by Django 5.2.12 on 2026-04-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_clinic_search_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="chain_detected_ai",
            field=models.BooleanField(
                default=False,
                help_text="True when Gemini flags multi-location / group signals from listing text.",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="chain_detected_internal",
            field=models.BooleanField(
                default=False,
                help_text="True when another row shares the same clinic name with a different address.",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="location_count_estimate",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional estimate from AI when sources mention several branches or cities.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="is_chain",
            field=models.BooleanField(
                default=False,
                help_text="True when multiple locations are inferred (DB name match and/or AI).",
            ),
        ),
    ]
