# Generated by Django 5.2.12 on 2026-04-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_chain_detection_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="whatsapp_draft",
            field=models.TextField(
                blank=True,
                help_text="Personalized opening message as a potential customer (e.g. for WhatsApp).",
            ),
        ),
    ]
