# Generated by Django 5.2.13 on 2026-04-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_rename_clinic_table_if_still_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Lead group',
                'verbose_name_plural': 'Lead groups',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_category_idx',
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='match_phrase',
            field=models.CharField(help_text='Substring matched against business name (case-insensitive).', max_length=200),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100, help_text='Lower number = higher priority (evaluated first).'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='chain_detected_internal',
            field=models.BooleanField(default=False, help_text='True when another row shares the same business name with a different address.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='has_mounjaro',
            field=models.BooleanField(default=False, help_text='Medical hunts: true when Mounjaro / tirzepatide / Zepbound is signaled for this listing.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_ai_processed',
            field=models.BooleanField(default=False, help_text='True once Gemini enrichment has been applied to this row.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='shop_keyword',
            field=models.CharField(blank=True, default='', help_text='Keyword the user entered before the hunt (e.g. fitness center, café).', max_length=160),
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='maps_query_default',
            field=models.CharField(blank=True, default='', help_text='Optional. Pre-fills the Maps search field when you pick this type; if empty, the keyword alone is used.', max_length=255),
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='name',
            field=models.CharField(help_text='Label and hunt keyword stored on imported leads (e.g. Medical clinic).', max_length=120, unique=True),
        ),
        migrations.AlterModelTable(
            name='categoryrule',
            table='leads_categoryrule',
        ),
        migrations.AlterModelTable(
            name='lead',
            table='leads_lead',
        ),
        migrations.AddField(
            model_name='lead',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional folder; ungrouped leads appear only under “All leads”.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadgroup'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['category'], name='leads_category_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['group'], name='leads_leadgroup_idx'),
        ),
    ]
