# Generated by Django 5.2 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0014_lead_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="HuntRefineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leads_analyzed", models.PositiveSmallIntegerField()),
                (
                    "suggested_shop_keyword",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "suggested_maps_query",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("patterns_summary", models.TextField(blank=True, default="")),
                ("what_to_avoid", models.TextField(blank=True, default="")),
                ("enrichment_tips", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hunt_refine_records",
                        to="leads.leadgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hunt refine record",
                "verbose_name_plural": "Hunt refine records",
                "db_table": "leads_huntrefinerecord",
                "ordering": ["-created_at"],
            },
        ),
    ]
