# Generated by Django 5.2 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0015_huntrefinerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="huntrefinerecord",
            name="secondary_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional second folder merged into the same analysis (e.g. “very potential”).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="leads.leadgroup",
            ),
        ),
        migrations.AddField(
            model_name="huntrefinerecord",
            name="secondary_leads_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="How many leads from secondary_group were included.",
            ),
        ),
    ]
