# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0017_leadgroup_sort_order_lead_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="is_very_important",
            field=models.BooleanField(
                default=False,
                help_text="User-flagged as very important (e.g. star on dashboard card).",
            ),
        ),
    ]
