# Generated by Django 5.2.13 on 2026-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_lead_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone (denormalized: first entry in phone_numbers).', max_length=64),
        ),
        migrations.AlterField(
            model_name='searchqueryrecord',
            name='search_country',
            field=models.CharField(blank=True, default='', help_text='Optional country to disambiguate the Serper hunt.', max_length=255),
        ),
    ]
