# Generated by Django 5.2.12 on 2026-04-28 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0021_alter_lead_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadConversationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_date",
                    models.DateField(
                        help_text="Date of the conversation or follow-up."
                    ),
                ),
                (
                    "remarks",
                    models.TextField(help_text="What happened in the conversation."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_logs",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead conversation log",
                "verbose_name_plural": "Lead conversation logs",
                "db_table": "leads_leadconversationlog",
                "ordering": ["-conversation_date", "-created_at", "-id"],
            },
        ),
    ]
