# Generated by Django 5.2.15 on 2026-06-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='whatsapp_instance_id',
            field=models.CharField(blank=True, default='', help_text='Meta Graph API phone number ID used for the last outbound dispatch.', max_length=120),
        ),
        migrations.AlterField(
            model_name='lead',
            name='whatsapp_last_error',
            field=models.TextField(blank=True, default='', help_text='Last Meta Cloud API / network error for automated WhatsApp dispatch.'),
        ),
    ]
