# Generated by Django 5.2.15 on 2026-06-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_whatsappconfig_meta_templates'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_cl_ai_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='ai_analysis',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='has_mounjaro',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_ai_processed',
        ),
    ]
