# Generated by Django 5.2.15 on 2026-06-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_remove_lead_leads_cl_ai_idx_remove_lead_ai_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBatchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When this batch should run (stored timezone-aware).')),
                ('lead_count', models.PositiveIntegerField(help_text='How many oldest PENDING leads to send when this batch runs.')),
                ('status', models.CharField(choices=[('pending', 'Scheduled'), ('processing', 'Sending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Leads actually dispatched when the batch ran.')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'WhatsApp batch schedule',
                'verbose_name_plural': 'WhatsApp batch schedules',
                'db_table': 'leads_whatsappbatchschedule',
                'ordering': ['-scheduled_at', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='send_cooldown_enabled',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='send_cooldown_seconds',
        ),
    ]
