# Generated by Django 5.2.15 on 2026-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_whatsappbatchschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappbatchschedule',
            name='outbound_template_name',
            field=models.CharField(default='just_to_say_hi', help_text='Meta-approved template this batch dispatches.', max_length=64),
        ),
    ]
