# Generated by Django 5.2.15 on 2026-06-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_whatsappbatchschedule_outbound_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappbatchschedule',
            name='lead_count',
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp_batch',
            field=models.ForeignKey(blank=True, help_text='Scheduled batch this lead will be sent in (assigned from the Queue).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.whatsappbatchschedule'),
        ),
    ]
