# Generated by Django 5.2.15 on 2026-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0042_whatsappconfig_free_text_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconfig',
            name='free_text_templates',
            field=models.JSONField(blank=True, default=list, help_text='Ordered Active Chat reply templates ({label, text}). Top 3 appear in the chat drawer.'),
        ),
    ]
