# Generated by Django 5.2.17 on 2026-08-24 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_user_profiles(apps, schema_editor):
    """Existing users (e.g. createsuperuser) need a profile; no username hardcoded."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model("leads", "UserProfile")
    for user in User.objects.all().iterator():
        UserProfile.objects.get_or_create(user=user, defaults={"role": "sales"})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0044_chatmessage_delivery_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Sales owner. Sales-role users only see leads assigned to them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sales', 'Sales'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='sales', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.RunPython(create_missing_user_profiles, noop_reverse),
    ]
