# Generated by Django 5.2.17 on 2026-08-27 07:45

from django.db import migrations, models

_M2M_INSERT_BATCH = 2000


def _copy_category_types_to_tags(apps, schema_editor):
    """Mirror every LeadCategoryType into Tag (idempotent on slug)."""
    Tag = apps.get_model("leads", "Tag")
    LeadCategoryType = apps.get_model("leads", "LeadCategoryType")
    for cat in LeadCategoryType.objects.all().iterator():
        Tag.objects.update_or_create(
            slug=cat.slug,
            defaults={
                "label": cat.label,
                "sort_order": cat.sort_order,
                "is_system": cat.is_system,
            },
        )


def _assign_lead_tags_from_category(apps, schema_editor):
    """Give each lead the Tag whose slug matches Lead.category (idempotent)."""
    Tag = apps.get_model("leads", "Tag")
    Lead = apps.get_model("leads", "Lead")
    Through = Lead.tags.through

    slug_to_tag_id = dict(Tag.objects.values_list("slug", "id"))
    if not slug_to_tag_id:
        return

    batch = []
    for lead_id, category in Lead.objects.values_list("pk", "category").iterator(
        chunk_size=_M2M_INSERT_BATCH
    ):
        tag_id = slug_to_tag_id.get(category)
        if tag_id is None:
            continue
        batch.append(Through(lead_id=lead_id, tag_id=tag_id))
        if len(batch) >= _M2M_INSERT_BATCH:
            Through.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []
    if batch:
        Through.objects.bulk_create(batch, ignore_conflicts=True)


def backfill_tags(apps, schema_editor):
    _copy_category_types_to_tags(apps, schema_editor)
    _assign_lead_tags_from_category(apps, schema_editor)


def reverse_tag_backfill(apps, schema_editor):
    """Drop mirrored tags (M2M through rows cascade). Safe to re-run forward after."""
    Tag = apps.get_model("leads", "Tag")
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0045_userprofile_and_lead_assigned_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier (lowercase, e.g. dental, gp).",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System tags (Unknown, Invalid) cannot be deleted.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "leads_tag",
                "ordering": ["sort_order", "label", "slug"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Multi-select tags (additive copy of category; unused by the live app yet).",
                related_name="leads",
                to="leads.tag",
            ),
        ),
        migrations.RunPython(backfill_tags, reverse_tag_backfill),
    ]
