# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0046_tag_and_lead_tags"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lead",
            name="leads_category_idx",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="category",
        ),
        migrations.DeleteModel(
            name="LeadCategoryType",
        ),
        migrations.AlterField(
            model_name="lead",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="User-managed classification tags (sole source of truth).",
                related_name="leads",
                to="leads.tag",
            ),
        ),
        migrations.AlterField(
            model_name="categoryrule",
            name="category",
            field=models.CharField(
                help_text="Tag slug assigned when the rule matches.",
                max_length=32,
            ),
        ),
    ]
