# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations


def swap_dental_gp_sort_order(apps, schema_editor):
    """Dental before GP so dual-tagged leads show Dental as the primary badge."""
    Tag = apps.get_model("leads", "Tag")
    Tag.objects.filter(slug="dental").update(sort_order=10)
    Tag.objects.filter(slug="gp").update(sort_order=30)


def unswap_dental_gp_sort_order(apps, schema_editor):
    Tag = apps.get_model("leads", "Tag")
    Tag.objects.filter(slug="dental").update(sort_order=30)
    Tag.objects.filter(slug="gp").update(sort_order=10)


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0047_drop_lead_category_and_leadcategorytype"),
    ]

    operations = [
        migrations.RunPython(swap_dental_gp_sort_order, unswap_dental_gp_sort_order),
    ]
