# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations


_DEFAULT_MATCH_RULE_PRIORITY = 100


def seed_missing_tag_match_rules(apps, schema_editor):
    """Give every Tag at least one CategoryRule (label as match phrase).

    Historical Tag.save() does not run custom model methods, so this duplicates
    Tag.ensure_default_match_rule for existing rows.
    """
    Tag = apps.get_model("leads", "Tag")
    CategoryRule = apps.get_model("leads", "CategoryRule")
    configured = set(
        CategoryRule.objects.values_list("category", flat=True).distinct()
    )
    to_create = []
    for tag in Tag.objects.all().iterator():
        if tag.slug in configured:
            continue
        phrase = (tag.label or "").strip()[:200]
        if not phrase:
            continue
        to_create.append(
            CategoryRule(
                match_phrase=phrase,
                category=tag.slug,
                priority=_DEFAULT_MATCH_RULE_PRIORITY,
            )
        )
        configured.add(tag.slug)
    if to_create:
        CategoryRule.objects.bulk_create(to_create)


def unseed_missing_tag_match_rules(apps, schema_editor):
    """Cannot distinguish backfilled rules from user-created label phrases."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0048_swap_dental_gp_sort_order"),
    ]

    operations = [
        migrations.RunPython(
            seed_missing_tag_match_rules,
            unseed_missing_tag_match_rules,
        ),
    ]
