# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations


class InvalidTagStillInUse(RuntimeError):
    """Raised instead of deleting invalid while leads still reference it."""


def remove_invalid_tag_and_unknown_rules(apps, schema_editor):
    Tag = apps.get_model("leads", "Tag")
    CategoryRule = apps.get_model("leads", "CategoryRule")
    Lead = apps.get_model("leads", "Lead")

    invalid = Tag.objects.filter(slug="invalid").first()
    if invalid is not None:
        lead_count = Lead.objects.filter(tags=invalid).count()
        if lead_count:
            raise InvalidTagStillInUse(
                f"Cannot delete the invalid tag: {lead_count} lead(s) still "
                "use it. Reassign those leads first."
            )
        CategoryRule.objects.filter(category="invalid").delete()
        invalid.delete()
    else:
        CategoryRule.objects.filter(category="invalid").delete()

    CategoryRule.objects.filter(category="unknown").delete()


def restore_invalid_tag(apps, schema_editor):
    Tag = apps.get_model("leads", "Tag")
    Tag.objects.get_or_create(
        slug="invalid",
        defaults={
            "label": "Invalid / irrelevant",
            "sort_order": 1,
            "is_system": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0049_seed_missing_tag_match_rules"),
    ]

    operations = [
        migrations.RunPython(
            remove_invalid_tag_and_unknown_rules,
            restore_invalid_tag,
        ),
    ]
